version: "3"

services:
  fastapi:
    image: ${FASTAPI_IMAGE}
    build:
      context: .
      dockerfile : ${FASTAPI_DOCKERFILE}
    restart: on-failure
    container_name: ${FASTAPI_CONTAINER}
    depends_on:
      - maria
      # ports:
      #   - ${FASTAPI_HOST_PORT}:10004
    volumes:
      - ${APP_DIR}:/app/was/app
      - ${REQUIREMENTS}:/app/was/requirements.txt
    entrypoint: ["python", "/app/was/app/main.py"]
    networks:
      - backend-network

  nginx:
    image: ${NGINX_IMAGE}
    container_name: ${NGINX_CONTAINER}
    depends_on:
      - fastapi
    restart: on-failure
    ports:
      - ${NGINX_HOST_PORT}:80
    volumes:
      - ${NGINX_CONF}:/etc/nginx/nginx.conf
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d
      - ${NGINX_LOGS}:/var/log/nginx
    networks:
      - backend-network

  maria :
    image: ${MARIADB_IMAGE}
    container_name: ${MARIADB_CONTAINER}
    restart: always
    ports:
      - ${MARIADB_PORT}:3306
    volumes:
      - ${MARIADB_CONF}:/etc/mysql/conf.d:ro
      - ${MARIADB_LIB}:/var/lib/mysql
      - ${MARIADB_LOG}:/var/log/maria
    environment:
      - TZ=${MARIADB_TZ}
      - ALLOW_EMPTY_PASSWORD=no
      - MARIADB_ROOT_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_DATABASE=${MARIADB_DB}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    networks:
      - backend-network

  adminer:
    image: ${ADMINER_IMAGE}
    container_name: ${ADMINER_CONTAINER}
    restart: always
    ports:
      - ${ADMINER_HOST_PORT}:8080
    depends_on:
      - maria
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
